const Types = {
  SET_POKEMON_LIST: 'SET_POKEMON_LIST',
  SET_POKEMON_DETAIL: 'SET_POKEMON_DETAIL',
  SET_POKEMON_DESCRIPTION: 'SET_POKEMON_DESCRIPTION',
  SET_POKEMON_TYPES: 'SET_POKEMON_TYPES',
  SET_POKEMON_FOR_BATTLE: 'SET_POKEMON_FOR_BATTLE',
  REMOVE_POKEMON_FROM_BATTLE: 'REMOVE_POKEMON_FROM_BATTLE',
};

export default Types;
